### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by incyi**
Add Github actions CI badge. My changes are based on the default branch. You can also specify the branch by adding this behind .svg.

?branch=master

### CODE REVIEW

**Comment by JF002** [comment]
Is it normal that it display the badge "no status"?

**Comment by incyi** [comment]
No, it should contain the status as "run" or "failed". Let's findout what is going wrong here.

Uhh, the CI is containing this:
# Run this workflow on every push and pull request on "master" branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

So it only works for the master branch. Do we want this also for the develop branch ?

**Comment by JF002** [comment]
New builds have been done on master branch, so the badge should now be available, but the link https://github.com/JF002/Pinetime/workflows/CI/badge.svg points nothing (`not found').

**Comment by incyi** [comment]
The link should be:

Build PineTime Firmware

**Comment by incyi** [comment]
Fixed, now it's ready.

**Comment by JF002** [comment]
Thanks for the update. However, IIRC, Github Actions only run on **master**. Should we display the badge from the master branch?

**Comment by incyi** [comment]
Changed back to master.

**Comment by JF002** [comment]
Hey Thanks! I was just reviewing older PRs, you did this last modification just in time :)

**Pull request merged**
