### PR TITLE
Continuous Integration with GitHub Actions

### PR DESCRIPTION
**Pull request by lupyuen**
Automatically builds the firmware on pushes and pull requests to the `master` branch.

Fixed the include paths in `TwiMaster.cpp`.

GitHub Actions build was tested successfully with `pinetime-lab` repo.

### CODE REVIEW

**Comment by JF002** [comment]
Is this a CI as a service provided by Github?

**Comment by lupyuen** [comment]
Yes it's free for public open source repos

**Comment by lupyuen** [comment]
Yes GitHub Actions is a free CI service for public open source repos. The script to auto build the repo is here:

https://github.com/lupyuen/pinetime-lab/blob/master/.github/workflows/c-cpp.yml

I'm thinking: Can we use this to simplify firmware builds for newbies? All the newbie needs to do...

1. Fork the repo to their GitHub accounts (must be a public repo)

1. Check in changes to the source files

1. GitHub Actions automatically builds the firmware with the updated source files. 

    Usually completes in 2 mins. First time is slower because it needs to cache the Arm Toolchain and nRF5 SDK.

1. They download the completed firmware via "Artifacts" of the build and flash the firmware with OpenOCD

All this without installing any build tools on their computers. Just a simple editor with git support, plus OpenOCD for Linux, macOS or Windows.

When newbies are ready for more advanced coding, they can follow the same steps as GitHub Actions to build the firmware themselves:

https://github.com/lupyuen/pinetime-lab/blob/master/.github/workflows/c-cpp.yml

If you think this is good for newbies, just merge the PR. I'll write an article to document the newbie procedure. Thanks :-)

**Comment by JF002** [comment]
I was going to ask if it would be possible to write some doc about it, but you're already on it ;)

I'll merge the pull request, but I still have 2 last questions:
 - Is is possible to build more than one target (pinetime-app, pinetime-mcuboot-app and pinetime-graphics) ? It looks like only pinetime-app is built for now.
 - Is it possible to call post-build actions like imgtool.py (from mcuboot, to convert the binary file into an mcuboot image) and adafruit-nrfutil (to convert the image into a dfu file)? It would be really useful because for now, we have to call thise scripts manually for the OTA, and this is error prone.

These points maybe ideas for improvements ;)

**Comment by JF002** [comment]
Oh I've noticed that you selected the master branch as target for the PR. Could you change it to develop ? I push into master only for creating releases.

I know, I need to document my branching system (feature branches are created from develop, all devs are merged into develop, and we merge develop into master when we want to generate a release and a tag).

Thanks!

**Comment by lupyuen** [comment]
Yep I'm quite sure we can do all these with GitHub Actions :-)

I'll go work on these for Continuous Integration for the repo:

1. Trigger builds from `develop` branch to `master`

1. Add builds for pinetime-app, pinetime-mcuboot-app and pinetime-graphics. Lemme find out how to build them.

1. Call post-build actions imgtool.py (from mcuboot, to convert the binary file into an mcuboot image) and adafruit-nrfutil (to convert the image into a dfu file). Lemme find out what needs to be done.

Meanwhile I'll write an article targeting newbies: How to fork this repo and set up GitHub Actions to auto-build this repo in the cloud.

I have a hunch that this might be really useful for newbies (so they can build firmware without any PC setup). But I will have to guide newbies into using this, and find out whether it works.

**Comment by incyi** [comment]
So if you go for this one, other ci/cd stuff can be rejected.

**Comment by JF002** [comment]
@incyi I see no reason to reject other CI/CD. This pull request is totally not intrusive and allows people to easily build their own version of the firmware without having to install the whole dev environment and I trust @lupyuen to write an extensive documentation about it.

My "dream" CI would be something simple that anyone can selfhost or setup on his/her own setup, but I haven't had the time yet to build this kind of CI :)

**Comment by JF002** [comment]
@lupyuen 

> Trigger builds from develop branch to master

In my previous comment, the 'develop' branch I was talking about was the target branch of this pull request (the branch where this one will be merged). I don't know which branch the CI should automatically, though.

In my branching system, I write new feature/fix bug in feature branch that are created from develop. When the work in done on these branches, I merge them into develop. And when I want to tag a new release, develop is merged into master.
But maybe the users of these Github action won't work the same way?

**Comment by JF002** [comment]
Merged manually to fix conflicts

**Pull request closed without merging**
