### PR TITLE
Create FUNDING.yml

### PR DESCRIPTION
**Pull request by Avamander**
Added a link to the LiberaPay donation page

### CODE REVIEW

**Comment by JF002** [comment]
Thanks ! I didn't know Github had this kind of integration!

However, I'm a bit reluctant to "advertise" my donation link on the project repo, because I'm not the only one working on it, but I would be the only one the receive the money.. What's your opinion?

**Comment by Avamander** [comment]
@JF002 

> However, I'm a bit reluctant to "advertise" my donation link on the project repo, because I'm not the only one working on it, but I would be the only one the receive the money.. What's your opinion?

It's fine. Replace it with a project link if there's an actual need.

**Comment by JF002** [comment]
Are there other projects where the 'creator' advertises its donation link while other people contribute to the project?

**Comment by Avamander** [comment]
@JF002 

> Are there other projects where the 'creator' advertises its donation link while other people contribute to the project?

Yes and I wouldn't say you aren't contributing enough.

**Comment by JF002** [comment]
Thanks!
I received my first donation, by the way ;)

**Pull request merged**
