### PR TITLE
Noticed this typo when booting my PineTime

### PR DESCRIPTION
**Pull request by robertecurtin**

### CODE REVIEW

**Comment by Avamander** [comment]
Pull requests are done towards the `develop` branch.

**Comment by ryanplusplus** [comment]
Is there a reason that `develop` isn't configured to be the default branch? That will make it much harder to accidentally create a PR against `master`.

**Comment by JF002** [comment]
Thanks for this PR. As @Avamander, PR should be done towards develop as explained [here](https://github.com/JF002/Pinetime/blob/master/doc/contribute.md#how-to-submit-a-pull-request-).

Default branch is a dilemma for me : users will want to see the current "stable" state of the project, which is represented by the **master** branch (lastest release), and developers will want to see the latest additions that were merged into the code (**develop**).

In the meantime, if you can change the target branch, I'll happily accept your PR ;)

**Comment by Avamander** [comment]
@JF002, though showing `develop` as the default might display more ongoing progress by default, which might be more attractive to new people.

**Comment by JF002** [comment]
Won't they be frustrated to see new functionalities that are not available yet in the released version?

**Comment by Avamander** [comment]
> Won't they be frustrated to see new functionalities that are not available yet in the released version?

Might, might just create something to look forward to.

**Comment by robertecurtin** [comment]
Thanks y'all, I've got it pointed at the right spot now.

Regarding user vs developer experience, you could host user-facing documentation with Github Pages and keep the github repo pointed at `develop`.

**Comment by JF002** [comment]
Thanks @robertecurtin and @Avamander I've changed the default branch of the repo to **develop** :)
And I'll merge this PR!

**Pull request merged**
