### PR TITLE
Update to nimble 1.3 master branch

### PR DESCRIPTION
**Pull request by JF002**
I created this PR to check if newer version of Nimble would improve BLE connection reliability.
Fow now, InfiniTime uses the last tagged version (1.3.0) of Nimble.
This branch updated nimble to the last commit in the master branch (not tagged).

I did many succesful OTA based on this branch. Anyone is free to test it and report success, failure, bugs or improvement :)

### CODE REVIEW

**Comment by JF002** [comment]
Here is a DFU build of this branch (WARNING : this is a test FW, use it with caution on sealed devices) [dfu-0.11.0.zip](https://github.com/JF002/Pinetime/files/5914489/dfu-0.11.0.zip)

**Comment by piggz** [comment]
If you have it connected to Amazfish and leave it for some time, does amazfish remain connected?

**Comment by petterhs** [comment]
This is massive! Thanks! While I had 4 or 5 failed OTA's just to get to this branch, I have yet to get a disconnect while OTA updating from this branch. Somewhere around 10 straight successful OTA updates. 

Pros: 
- The recovery/restart of the update after an error is working. (Though with a visual bug) Before when i got an error I absolutely had to reboot the watch but now it reconnects automatically and retries the update.

Cons:
- Visual bug that persists across screens. Happens when OTA update starts while the watch is on the error screen, either automatically or manually.
- Hard to debug above bug because it never disconnects...lol. I have to walk to the other side of my apartment.

**Comment by piggz** [comment]
After flashing with amazfish on my phone, I paired with my desktop and it has maintained a connection for over 30 minutes now.

**Comment by JF002** [comment]
My devkit stayed connected the whole day with my Android phone! 

So, it looks like this upgrade improved the situation by a lot! I guess I'll clean the code, merge the branch and release a new version soon :)

**Comment by JF002** [comment]
I pushed an update to re-enable the heart rate task. Here is the dfu.
[dfu-0.11.0-test.zip](https://github.com/JF002/Pinetime/files/5921275/dfu-0.11.0-test.zip)

**Pull request merged**
