### PR TITLE
Unify the Dockerfiles by fleshing out build.sh

### PR DESCRIPTION
**Pull request by Nuxij**
Script is written to handle it's own dependencies so it can be used within Docker or on the host system.

Handling dependencies within the script allows easy sharing of version information. This means the script can check its platform and use the relevant compiler etc at run time, downloading them if necessary.

Dockerfile then need only supply system level dependencies, that do not clash between architectures, and forget caring about the architecture altogether.

### CODE REVIEW

**Comment by Nuxij** [comment]
Just spotted #137, I will have to look at integrating some of that here!

**Comment by JF002** [comment]
Thanks for this PR, it looks really good to me!
@Nuxij could you try to fix the conflicts that appeared when I merge https://github.com/JF002/Pinetime/pull/137 ?
@pfeerick could you have a look at this PR, since you've already contributed to the docker files?

**Comment by Nuxij** [comment]
@JF002 Thanks! Should be sorted now :)

**Comment by pfeerick** [comment]
In principle looks good to me... I've yet to run it though... so famous last words. 😆 I like that you've been able to consolidate all the environment specific stuff into the main build script, making it so the docker builds are platform agnostic. If I find some time tomorrow I'll update my dockerhub builds to use this so it can get some more testing. 

Looks like you've appeased Github at last... can be a fussy beast at times! 😮

**Comment by Nuxij** [comment]
I have also yet to test it on an actual ARM machine, so my platform check might be bogus! Good Luck! 😄

**Comment by pfeerick** [comment]
The docker hub builds for this PR are now available at `pfeerick/infinitime-build:pr149-amd64` and `pfeerick/infinitime-build:pr149-arm64v8`

While they both build and run fine, note that at the end of both, they don't seem to run the post-build stage automatically?

```
[100%] Linking CXX executable pinetime-app-0.9.0.out
post build steps for pinetime-app-0.9.0
   text    data     bss     dec     hex filename
 271004     728   36504  308236   4b40c pinetime-app-0.9.0.out
[100%] Built target pinetime-app
+ [[ '' != \t\r\u\e ]]
+ source /sources/build/post_build.sh
/opt/build.sh: line 33: /sources/build/post_build.sh: No such file or directory
+ echo 'Sourced!'
Sourced!
```

as opposed to 

```
[100%] Built target pinetime-mcuboot-app
+ sh /sources/docker/post_build.sh
+ mkdir -p /sources/build/output
+ /opt/mcuboot/scripts/imgtool.py create --align 4 --version 1.0.0 --header-size 32 --slot-size 475136 --pad-header /sources/build/src/pinetime-mcuboot-app-0.9.0.bin /sources/build/output/image-0.9.0.bin
+ adafruit-nrfutil dfu genpkg --dev-type 0x0052 --application /sources/build/output/image-0.9.0.bin /sources/build/output/dfu-0.9.0.zip
Zip created at /sources/build/output/dfu-0.9.0.zip
+ cp /sources/build/src/pinetime-app-0.9.0.bin /sources/build/src/pinetime-graphics-0.9.0.bin /sources/build/src/pinetime-mcuboot-app-0.9.0.bin /sources/build/output/
+ cp /sources/build/src/pinetime-app-0.9.0.hex /sources/build/src/pinetime-graphics-0.9.0.hex /sources/build/src/pinetime-mcuboot-app-0.9.0.hex /sources/build/output/
+ cp /sources/build/src/pinetime-app-0.9.0.out /sources/build/src/pinetime-graphics-0.9.0.out /sources/build/src/pinetime-mcuboot-app-0.9.0.out /sources/build/output/
+ cp /sources/build/src/pinetime-app-0.9.0.map /sources/build/src/pinetime-graphics-0.9.0.map /sources/build/src/pinetime-mcuboot-app-0.9.0.map /sources/build/output/
+ cp /sources/bootloader/bootloader-5.0.4.bin /sources/build/output/bootloader.bin
```
It is the same for both architectures. 

I think it is because the template for post build is in the source/docker folder, not the source/build folder?

**Comment by Nuxij** [comment]
Oooooh yes that is an old change I keep reintroducing by accident . Two seconds

**Comment by pfeerick** [comment]
... and 14 hours later :-P

Tried out latest changes on amd64, LGTM. And yes, that post_build output does nicer! :) 

Just waiting for the PBP to finish rebuilding the image so I can test it and push it to dockerhub. Will update shortly.

**Comment by JF002** [comment]
Thanks, @Nuxij @pfeerick for this great work and review!

It looks good to me and works fine on my desktop and PinebookPro. 
Just one question (because I don't know docker very well) : the updated doc says we need to run the container with `-it` parameter. As far as I know, this flag is used to run allocate a tty to enter 'into' the container. Why is it needed and... why, in the end, doesn't the container run in interactive mode?

**Comment by pfeerick** [comment]
@JF002 ... I noticed that also and ignored it altogether, hence why forgot to ask about that also! 😆

**Comment by Nuxij** [comment]
`-i` Is required if you want to send `CTRL+C` in my experience. The -t probably could be dropped, but "--rm -it" is in my muscle memory is all 🙂

**Comment by pfeerick** [comment]
Ah... learnt sumthin' new! :) And some trial and error suggests you need both the `-i` and the `-t` ... doing `-i` on it's own results in <kbd>Ctrl + C</kbd> doing squat other than looking pretty on the screen, doing `-it` make it actually terminate with extreme prejudice! 😮 😆

**Comment by JF002** [comment]
Good enough, thanks!

**Pull request merged**
