### PR TITLE
Redesigned and improved the Music watchapp

### PR DESCRIPTION
**Pull request by Avamander**
This PR redesigns the Music watchapp, it:

1. A sweet (tiny) animation to indicate playback

2. It shows track progress (even with 1.25x or 2x playback speed!)

3. It has very sweet gestures, swipe left or right for seeking, up or down to switch button functionality

4. Allows pushing a lot more data to the watch (allows extending the watchapp to display loop/repeat status)

5. Adds license headers to the new files, it's not super mandatory, but it seems nicer to me, more "official" :D 

6. Formats the files and renames variable names according to the agreed code style

### CODE REVIEW

**Comment by Avamander** [comment]
Demo video: https://www.youtube.com/watch?v=YvER1JsuPOg

**Comment by JF002** [comment]
Nice UI improvements on the Music app, thanks!

On my system, the Music app does not build:

```
/home/jf/git/Pinetime/src/displayapp/screens/Music.cpp: In constructor 'Pinetime::Applications::Screens::Music::Music(Pinetime::Applications::DisplayApp*, Pinetime::Controllers::MusicService&)':
/home/jf/git/Pinetime/src/displayapp/screens/Music.cpp:108:3: error: 'lv_img_set_src_arr' was not declared in this scope; did you mean 'lv_img_set_src'?
  108 |   lv_img_set_src_arr(imgDisc, &disc);
      |   ^~~~~~~~~~~~~~~~~~
      |   lv_img_set_src
make[3]: *** [src/CMakeFiles/pinetime-app.dir/build.make:291 : src/CMakeFiles/pinetime-app.dir/displayapp/screens/Music.cpp.o] Erreur 1
```

Howevery, it builds if I replace calls to `lv_img_set_src_arr()` by `lv_img_set_src()`.

I noticed that the progress was not working (it displays `00:00/00:00` even if music is playing on my phone). I guess this is because Gadgetbridge v0.47.2 does not implement that functionality?

**Comment by Avamander** [comment]
> Howevery, it builds if I replace calls to lv_img_set_src_arr() by lv_img_set_src().

Ah, right, I wanted to add a new function to LVGL that does type checking properly (the `lv_img_set_src` function takes `void *` which caused me an hour of pointless googling). 

> I noticed that the progress was not working (it displays 00:00/00:00 even if music is playing on my phone). I guess this is because Gadgetbridge v0.47.2 does not implement that functionality?

Yes, the time will be updated in the next release of Gadgetbridge (v0.48.0).

**Comment by JF002** [comment]
You can add the function, I also like strongly typed code :) Maybe you can add it as a free function to avoid modification into the code fro lvgl?

**Comment by Avamander** [comment]
> You can add the function, I also like strongly typed code :) Maybe you can add it as a free function to avoid modification into the code for lvgl?

Done.

**Pull request merged**
