### PR TITLE
Fix TwiMaster lockup

### PR DESCRIPTION
**Pull request by TT-392**
This should fix the TWIM lockup problem. 

I left the timeout at 5000, in my testing this seems to be a number that isn't really noticeable, but also seems to not false trigger.

I did leave in a static global variable for the twimaddress and 2 hardcoded pins (line 75), good chance that this isn't the best way of doing this here. But that is probably best fixed by someone who knows more about C++ than me.

### CODE REVIEW

**Comment by JF002** [comment]
Thanks for this fix! I think the code could be slightly modified to look a bit  more like C++ and avoid the static global variable. I'll try to have a look soon!

Also, do you think [this comment](https://github.com/JF002/Pinetime/issues/79#issuecomment-706568547) correspond to this bug, and that we can try to fix the issue using the workaround from the NRF anomaly documentation?

**Comment by TT-392** [comment]
> Thanks for this fix! I think the code could be slightly modified to look a bit more like C++ and avoid the static global variable. I'll try to have a look soon!
> 
> Also, do you think [this comment](https://github.com/JF002/Pinetime/issues/79#issuecomment-706568547) correspond to this bug, and that we can try to fix the issue using the workaround from the NRF anomaly documentation?

It might be related. But I wouldn't be surprised if it is specifically a twim issue or maybe even related to the slave device getting stuck though. 

I think I also, found the nordic forum thread where I originally got the idea for this fix:
https://devzone.nordicsemi.com/f/nordic-q-a/23601/twi-stops-working---sda-bus-always-low

**Comment by JF002** [comment]
@TT-392 Thank you very much for your PR and for all the information you provided in this PR and in https://github.com/JF002/Pinetime/issues/79, they were invaluable.
I've eventually implemented your fix in a C++ way in https://github.com/JF002/Pinetime/pull/111. I hope you don't mind if I close this one?

**Comment by TT-392** [comment]
Sounds good

**Comment by JF002** [comment]
Merged and release in 0.9.0. Thanks!

**Pull request closed without merging**
