### PR TITLE
WIP: LVGL v7 and dependencies turned into submodules

### PR DESCRIPTION
**Pull request by Avamander**
This **Work in Progress** PR is for the LVGLv6->LVGLv7 migration plus it turns a bunch of dependencies into submodules.

If you have fixes or improvements, make a PR to **Avamander/PineTime:lvgl-v7**. If you do, there's hope it's completed sooner :)

### CODE REVIEW

**Comment by redengin** [comment]
My preference is to leverage CMake::FetchContent https://cmake.org/cmake/help/latest/module/FetchContent.html, rather than make developers manage git submodules.

**Comment by redengin** [comment]
the current commit modifies many files - whereas a dependency refactor would be expected to be mostly deletion of files and additions of files that provide the source (via git submodule.

**Comment by Avamander** [comment]
@redengin 

> My preference is to leverage CMake::FetchContent https://cmake.org/cmake/help/latest/module/FetchContent.html, rather than make developers manage git submodules.

I've come to a similar conclusion, mostly because NimBLE has a very annoying configuration system.

**Comment by Avamander** [comment]
@redengin 

> the current commit modifies many files - whereas a dependency refactor would be expected to be mostly deletion of files and additions of files that provide the source (via git submodule.

I planned on splitting off the dependency refactoring to a separate PR. Dep RF doesn't however require waiting for me.

**Pull request closed without merging**
